name: Build-Windows-EXE

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --clean --onefile ^
            --name MapKordi ^
            --add-data "src/app;app" ^
            --hidden-import=tkinterdnd2 ^
            src/main.py

      - name: Pack artifact
        run: |
          mkdir out
          copy dist\MapKordi\MapKordi.exe out\MapKordi.exe
          copy README.md out\README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: MapKordi-Windows-zip
          path: out
